# Generated by Django 3.2.7 on 2021-10-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
