# Generated by Django 3.2.7 on 2021-10-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_plan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
