# Generated by Django 3.2.7 on 2021-10-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_plan_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='rate',
        ),
    ]
