# Generated by Django 3.2.7 on 2021-10-27 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_plan_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='example',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='english',
            name='meaning',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='english',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='english',
            name='word',
            field=models.CharField(max_length=20),
        ),
    ]
