# Generated by Django 3.2.7 on 2021-10-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211027_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english',
            name='example',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='english',
            name='meaning',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
