# Generated by Django 3.2.9 on 2021-11-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20211028_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='type',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='english',
            name='example',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
