# Generated by Django 3.2.9 on 2021-12-15 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20211109_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_todo', models.DateField()),
                ('Task_todo', models.TextField(max_length=50, null=True)),
                ('Check_done', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week_todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.list_todo')),
            ],
        ),
    ]
