# Generated by Django 3.2.9 on 2021-12-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20211220_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week_todo',
        ),
    ]
