# Generated by Django 3.2.9 on 2021-12-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_delete_week_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_todo',
            name='Time_todo',
            field=models.IntegerField(null=True),
        ),
    ]
