# Generated by Django 3.2.9 on 2021-12-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_list_todo_time_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_todo',
            name='Check_done',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='list_todo',
            name='Day_todo',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='list_todo',
            name='Task_todo',
            field=models.TextField(default=0.00024740227610094015, max_length=50),
            preserve_default=False,
        ),
    ]
