# Generated by Django 3.2.9 on 2021-12-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20211225_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_todo',
            name='Check_done',
            field=models.BooleanField(default=False),
        ),
    ]
