# Generated by Django 3.2.9 on 2022-01-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_plan_time_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_todo',
            name='Time_todo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='time_todo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
