# Generated by Django 3.2.9 on 2022-01-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20220116_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='period_day',
            field=models.IntegerField(default=1),
        ),
    ]
