# Generated by Django 3.2.9 on 2022-01-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_note_period_re'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Period_re',
        ),
    ]
